name: Test Home Assistant Add-on Build

on:
  push:
    branches: [ main, master ]
    paths:
      - 'ambientika-local-control/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'ambientika-local-control/**'

jobs:
  test-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        arch: [amd64, aarch64, armv7]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Home Assistant Add-on
      uses: docker/build-push-action@v5
      with:
        context: ./ambientika-local-control
        platforms: linux/${{ matrix.arch == 'amd64' && 'amd64' || matrix.arch == 'aarch64' && 'arm64' || 'arm/v7' }}
        build-args: |
          BUILD_ARCH=${{ matrix.arch }}
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Test add-on configuration
      run: |
        # Validate config.yaml syntax
        python3 -c "
        import yaml
        with open('ambientika-local-control/config.yaml', 'r') as f:
            config = yaml.safe_load(f)
        print('✅ Config validation passed')
        print(f'Add-on: {config[\"name\"]} v{config[\"version\"]}')
        print(f'Architectures: {config[\"arch\"]}')
        "

  validate-structure:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Validate add-on structure
      run: |
        echo "🔍 Checking add-on structure..."
        
        # Check required files
        required_files=(
          "ambientika-local-control/config.yaml"
          "ambientika-local-control/Dockerfile" 
          "ambientika-local-control/README.md"
          "ambientika-local-control/run.sh"
          "repository.yaml"
        )
        
        for file in "${required_files[@]}"; do
          if [[ -f "$file" ]]; then
            echo "✅ $file exists"
          else
            echo "❌ Missing required file: $file"
            exit 1
          fi
        done
        
        # Check source files
        if [[ -d "ambientika-local-control/src" ]]; then
          echo "✅ Source directory exists"
          echo "📁 Source files: $(find ambientika-local-control/src -name "*.ts" | wc -l) TypeScript files"
        else
          echo "❌ Missing src directory"
          exit 1
        fi
        
        echo "🎉 Add-on structure validation passed!"